FROM php:7.1-fpm

RUN touch /usr/local/etc/php/conf.d/999-custom.ini && \
    echo date.timezone="Europe/Moscow" >> /usr/local/etc/php/conf.d/999-custom.ini && \
    rm /etc/localtime && \
    ln -s /usr/share/zoneinfo/Europe/Moscow /etc/localtime && \
    apt-get update && \
    apt-get install -y \
    git \
    unzip \
    libxml2-dev \
    libcurl4-gnutls-dev \
    libicu-dev \
    default-jre \
    libfreetype6-dev \
    libjpeg62-turbo-dev \
    libmcrypt-dev \
    libpng12-dev \
    libpq-dev && \
    docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql && \
    docker-php-ext-install pdo && \
    docker-php-ext-install pdo_pgsql && \
    docker-php-ext-install pgsql && \
    docker-php-ext-install pcntl && \
    docker-php-ext-install gettext && \
    docker-php-ext-install mbstring && \
    docker-php-ext-install gettext && \
    docker-php-ext-install curl && \
    docker-php-ext-install xmlwriter && \
    docker-php-ext-install intl && \
    docker-php-ext-install gd && \
    docker-php-ext-install bcmath && \
    pecl install xdebug && \
    docker-php-ext-enable xdebug && \
    echo "error_reporting = E_ALL" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "display_startup_errors = On" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "display_errors = On" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "max_execution_time=600" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.enable=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.remote_enable=1" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.remote_connect_back=0" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.idekey=\"PHPSTORM\"" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "xdebug.remote_port=9001" >> /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && \
    echo "php_admin_value[log_errors]=1" >> /usr/local/etc/php-fpm.d/www.conf && \
    echo "php_admin_value[error_log]=/var/log/php_errors.log" >> /usr/local/etc/php-fpm.d/www.conf

WORKDIR /intercity-backend
