version: '3.2'

services:

  nginx:
    build:
      context: ./
      dockerfile: ./nginx/Dockerfile.dev
    ports:
      - "8888:80"
    volumes:
      - ../intercity-backend:/intercity-backend:rw
      - ./nginx/site.conf.dev:/etc/nginx/conf.d/site.conf
    links:
      - php-fpm

  php-fpm:
    build:
      context: ./
      dockerfile: ./php-fpm/Dockerfile.dev
    volumes:
      - ../intercity-backend:/intercity-backend:rw
    environment:
      XDEBUG_CONFIG: remote_host=${XDEBUG_HOST_IP}
    depends_on:
      - postgres

  postgres:
    build:
      context: ./
      dockerfile: ./postgres/Dockerfile.dev
    env_file:
      - ./.env

#    ports:
#      - "5432:5432"
